'use client'
import './globals.css';
import { League_Spartan } from 'next/font/google'

const LeagueSpartan = League_Spartan({ subsets: ['latin'], weight: '700' });

export const metadata = {
  title: 'Calculator App',
  description: 'Generated by create Calculator App',
}

const backgroundTheme = 'bg-theme1-main-background'

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`
      ${backgroundTheme}
      flex 
      items-center 
      justify-center  
      w-full
      h-full
      text-4xl
      ${LeagueSpartan.className}`}>{children}</body>
    </html>
  )
}
